### ISSUE TITLE
Contributors section looks strange

### ISSUE THREAD

**Issue by andrewda** [gitpoint/git-point-site#11]
![screen shot 2017-09-23 at 4 18 27 pm](https://user-images.githubusercontent.com/10191084/30777920-3516c42c-a07b-11e7-9dc2-8aad06591179.png)

I can play around with the CSS in a bit to try and fix this up.

**Comment by housseindjirdeh** [comment]
Ah interesting, I don't see that but I see a very _squeezed_ section: 

![image](https://user-images.githubusercontent.com/12476932/30778477-f0013028-a0a4-11e7-8d7b-8e2e27745fba.png)

ut I'm on a 15'' Mac, reducing my browser window see's the wrap messing up:

![image](https://user-images.githubusercontent.com/12476932/30778480-fd6efbc8-a0a4-11e7-8a9e-ed58da5c4860.png)

Really appreciate you logging this issue. I think we need to find a better way to show contributors as we're only going to get more and more. Also toying with the CSS right now to see if there's a simple way
