### ISSUE TITLE
Add a proper contributors section

### ISSUE THREAD

**Issue by housseindjirdeh** [gitpoint/git-point-site#3]
This project is only becoming what it is thanks to its amazing community. We need to have a nice contributors section in our footer and I think what I did for [hnpwa.com](https://hnpwa.com/) will be perfect :)

**Comment by andrewda** [comment]
This sounds like a fantastic idea! Should be able to do this completely in JS by getting the JSON list of contributors from https://raw.githubusercontent.com/gitpoint/git-point/master/.all-contributorsrc and rendering that to the footer 😄

**Comment by housseindjirdeh** [comment]
I was literally just thinking about how I can make this dynamic 🤔 

Thanks a million mate this is _definitely_ something we can do 🙌
