### ISSUE TITLE
Update contributors

### ISSUE THREAD

**Issue by CameronSamuels** [gitpoint/git-point-site#8]
Currently there are 31 contributors, but only 21 on the GitPoint site.

**Comment by andrewda** [comment]
Hmm... 🤔 

It _should_ be dynamic from the main repo (https://github.com/housseindjirdeh/git-point-site/blob/51ee44723f570f25e005f1f57459b77ef77535a2/_includes/footer.html#L6-L29). Could it be cached? Is this not the live version of the site (@housseindjirdeh)?

**Comment by andrewda** [comment]
AH may have found the issue: https://travis-ci.org/gitpoint/git-point-site/builds/260762264#L695

I think we'll need `npm install -g firebase-tools` in the Travis install step.

**Comment by housseindjirdeh** [comment]
Thanks so much for spotting this @CameronSamuels. 

I owe you one @andrewda, really appreciate you digging into the config and spotting that I missed that step :scream:

**Comment by andrewda** [comment]
Looks like the _real_ issue here was that the JSON was broken (fixed here: https://github.com/gitpoint/git-point/commit/b75e00425d0350737112cd3bcf28efdd9c7487d4).
